### ISSUE TITLE
Font makes values hard to read.

### ISSUE THREAD

**Issue by esbeto** [stefanrush/weightof.it#4]
I don't know if I'm the only one, but the Raleway font makes it hard to read values at first glance.

For example I was confused about the value for backbone:

![74or7dot4](https://cloud.githubusercontent.com/assets/1455236/8622068/dcf12380-26ee-11e5-8c94-932bda0153ff.png)

**Comment by stefanrush** [comment]
I definitely agree. I never really considered it because I got so used to Raleway.

I just tried adjusting the letterspacing, but it still didn't look right. I think I'm going to use a monospaced font for the weights only. What do you think of the 300 point version of this?

https://www.google.com/fonts/specimen/Roboto+Mono
![roboto](https://cloud.githubusercontent.com/assets/1662015/8624114/919a75ca-2703-11e5-8d93-72ecccf83756.png)

**Comment by esbeto** [comment]
I tried Droid Sans Mono, Source Code Pro 300, Inconsolata, and Roboto Mono 300. In my opinion the best options are Inconsolata and Roboto Mono. Buy maybe I would gear towards Roboto because of the lighter weight. It's more close to the design aesthetic.

**Comment by stefanrush** [comment]
Alright, the font change is live. I ended up going with Roboto. I really appreciate your input. Thank you!
