### ISSUE TITLE
Gzip calculation

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [stefanrush/weightof.it#5]
Hi, very interesting project.

I see that js-cookie is listed as having a gzip size of 916 bytes at http://weightof.it/category/utilities.

In the build I am using [grunt-compare-size to calculate the GZipped size](https://github.com/js-cookie/js-cookie/blob/d9318bb5994db77c809a6b26266b1ea84a42a40f/Gruntfile.js#L88-L99) and it prints the following for https://github.com/js-cookie/js-cookie/commit/d9318bb5994db77c809a6b26266b1ea84a42a40f:

![image](https://cloud.githubusercontent.com/assets/835857/9265869/af7806d0-420f-11e5-8f85-d61044ca5fb5.png)

As you see it says it has 856 bytes gzipped.

Using [closure compiler](http://closure-compiler.appspot.com/home) it shows the correct gzipped size in the "original size" section:

![image](https://cloud.githubusercontent.com/assets/835857/9265914/73180e3c-4210-11e5-92db-0b49555d2d4e.png)

[refresh-sf.com](http://refresh-sf.com/) also doesn't get even close to 900 bytes:

![image](https://cloud.githubusercontent.com/assets/835857/9265926/b92988e2-4210-11e5-9f2f-63a3bf05c6b5.png)

**Ok, but did you reduced the size recently?**

As a matter of fact [we did](https://github.com/js-cookie/js-cookie/commit/6b896ce02064efae60ea1e2f1617fa1853c8a708), but even then it never overflown to 900+ byte size.

**Why bother?**

We try to be as lightweight as possible, it is [even documented](https://github.com/js-cookie/js-cookie/tree/d9318bb5994db77c809a6b26266b1ea84a42a40f#javascript-cookie--) that the lib is ~800 bytes gzipped. In this case I would like to make sure that the calculation is being done correctly  to prevent misleading documentation in the README.md :)

How is the gzip calculation being done to show those numbers in the site?

**Comment by stefanrush** [comment]
Hey, I don't know how I missed this. Thanks for taking interest in the project. I'm using [Zlib](http://ruby-doc.org/stdlib-2.1.1/libdoc/zlib/rdoc/index.html) for compression. Relevant code is here:

https://github.com/stefanrush/weightof.it/blob/development/lib/scale.rb

I think the difference in size is due to differences in libraries and compression levels. I'm using the default compression level for Zlib (6/9), which was admittedly an oversight. What's interesting is Zlib seems to compress some of the larger libraries more than the tools you linked to. I would chalk this up to differences in compression algorithms between libraries. I may change the compression level to 9 and reweigh the database at some point.

**Comment by FagnerMartinsBrack** [comment]
Hi @stefanrush. It would be very useful to use some sort of "standard" GZIP algorithm that most tools also use, that would prevent this kind of problem.

**Comment by stefanrush** [comment]
To my knowledge zlib is the standard library for gzip compression in Ruby. Would you recommend a different library?

**Comment by FagnerMartinsBrack** [comment]
I don't write Ruby so I am not aware that zlib is the standard library for that language. What I mean is try to use an optimistic tool that compress better, maybe zlib 9/9 will do that, w/e.

**Comment by FagnerMartinsBrack** [comment]
Unfortunately I don't know a better tool other than [`gzip-js`](npmjs.com/package/gzip-js) that I am using on js-cookie....
